name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04  # Daha kararlı sürüm

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer Action
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          # buildozer.spec dosyanın olduğu klasör (ana dizin ise . kalsın)
          workdir: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Supreme-Terminal-V16
          path: bin/*.apk
